"""Intitial schema

Revision ID: cbd26f9a0d80
Revises: 
Create Date: 2026-03-31 14:33:55.669682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd26f9a0d80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 3', name='ck_study_items_difficulty'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_study_items_item_id'), 'study_items', ['item_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 1 AND confidence <= 3', name='ck_reviews_confidence'),
    sa.CheckConstraint('correct IN (0, 1)', name='ck_reviews_correct'),
    sa.CheckConstraint('response_time >= 0', name='ck_reviews_response_time'),
    sa.ForeignKeyConstraint(['item_id'], ['study_items.item_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_study_items_item_id'), table_name='study_items')
    op.drop_table('study_items')
    # ### end Alembic commands ###
