"""add user answer to reviews

Revision ID: e0f6efa7f5ac
Revises: 67849c7f554c
Create Date: 2026-10-02 17:25:07.519200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f6efa7f5ac'
down_revision: Union[str, Sequence[str], None] = '67849c7f554c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'user_answer')
    # ### end Alembic commands ###
